insert into MARKI values ('0', 'Carroll PLC');
insert into MARKI values ('1', 'Smith, Blackwell and Graham');
insert into MARKI values ('2', 'Miller Ltd');
insert into MARKI values ('3', 'Myers-Lopez');
insert into MARKI values ('4', 'Archer, Williams and Davis');
insert into MARKI values ('5', 'Sexton-Davis');
insert into MARKI values ('6', 'Roach, Smith and Brown');
insert into MARKI values ('7', 'Cannon-Lucas');
insert into MARKI values ('8', 'Gay, Farmer and Waller');
insert into MARKI values ('9', 'Rodriguez, Green and Howard');
insert into MARKI values ('10', 'Dunn, James and Mcdaniel');
insert into MARKI values ('11', 'Rogers, Perez and Skinner');
insert into MARKI values ('12', 'Howell Ltd');
insert into MARKI values ('13', 'Gardner-Walsh');
insert into MARKI values ('14', 'Gibson-Finley');
insert into MARKI values ('15', 'White, Larson and Hall');
insert into MARKI values ('16', 'Riley-Guerrero');
insert into MARKI values ('17', 'Clay-Hernandez');
insert into MARKI values ('18', 'Munoz Group');
insert into MARKI values ('19', 'Kirby-Miller');
insert into MARKI values ('20', 'Edwards-Johnson');
insert into MARKI values ('21', 'Hoffman, Spencer and Smith');
insert into MARKI values ('22', 'Nguyen, Osborn and Preston');
insert into MARKI values ('23', 'Swanson, Rice and Dickson');
insert into MARKI values ('24', 'Luna and Sons');
insert into MARKI values ('25', 'West Ltd');
insert into MARKI values ('26', 'Webster, Stark and Stone');
insert into MARKI values ('27', 'Montgomery Group');
insert into MARKI values ('28', 'Nichols PLC');
insert into MARKI values ('29', 'Simmons, Miranda and Chapman');
insert into MARKI values ('30', 'Glass Group');
insert into MARKI values ('31', 'Fleming Group');
insert into MARKI values ('32', 'Steele, Cline and Wilson');
insert into MARKI values ('33', 'Rice-Maddox');
insert into MARKI values ('34', 'Patel Ltd');
insert into MARKI values ('35', 'Anderson, King and Robinson');
insert into MARKI values ('36', 'Smith-Thomas');
insert into MARKI values ('37', 'Miller LLC');
insert into MARKI values ('38', 'Lewis-Fisher');
insert into MARKI values ('39', 'Morales, Moore and Rosales');
insert into MARKI values ('40', 'Gregory LLC');
insert into MARKI values ('41', 'Whitehead-Cook');
insert into MARKI values ('42', 'Sparks Inc');
insert into MARKI values ('43', 'Walker-Thomas');
insert into MARKI values ('44', 'Everett-Murray');
insert into MARKI values ('45', 'Good and Sons');
insert into MARKI values ('46', 'Butler-Smith');
insert into MARKI values ('47', 'Wade, Mann and Ball');
insert into MARKI values ('48', 'Cunningham, Williams and Berry');
insert into MARKI values ('49', 'Walsh Ltd');
insert into MARKI values ('50', 'Johnson-Perez');
insert into MARKI values ('51', 'Dorsey-Lawson');
insert into MARKI values ('52', 'House Group');
insert into MARKI values ('53', 'White, Ramsey and Perry');
insert into MARKI values ('54', 'Davis-James');
insert into MARKI values ('55', 'Roberts, Brown and Jenkins');
insert into MARKI values ('56', 'Bailey, Hernandez and Watson');
insert into MARKI values ('57', 'Williams, Richards and Jackson');
insert into MARKI values ('58', 'Lopez-Benson');
insert into MARKI values ('59', 'Cabrera-Evans');
insert into MARKI values ('60', 'Marks-Perez');
insert into MARKI values ('61', 'Rojas, Davis and Glover');
insert into MARKI values ('62', 'Dixon, Villa and Lopez');
insert into MARKI values ('63', 'Cox, Johnson and Matthews');
insert into MARKI values ('64', 'Frazier Group');
insert into MARKI values ('65', 'King, Chapman and Alexander');
insert into MARKI values ('66', 'Daniel, Vasquez and Cross');
insert into MARKI values ('67', 'Herman-Roberts');
insert into MARKI values ('68', 'Walker Group');
insert into MARKI values ('69', 'Carter PLC');
insert into MARKI values ('70', 'Bailey, Lambert and Smith');
insert into MARKI values ('71', 'Potter-Martinez');
insert into MARKI values ('72', 'Davidson-Glover');
insert into MARKI values ('73', 'Adams, Wilson and Anderson');
insert into MARKI values ('74', 'Dunn, Ingram and Lawson');
insert into MARKI values ('75', 'Lee, Hart and Williams');
insert into MARKI values ('76', 'Jones-Wise');
insert into MARKI values ('77', 'Moore-Holt');
insert into MARKI values ('78', 'Rogers PLC');
insert into MARKI values ('79', 'Flores PLC');
insert into MARKI values ('80', 'Collins-Malone');
insert into MARKI values ('81', 'Miller-Skinner');
insert into MARKI values ('82', 'Jones Inc');
insert into MARKI values ('83', 'Woods, Mitchell and Koch');
insert into MARKI values ('84', 'Harris-Miller');
insert into MARKI values ('85', 'Weaver, Brown and Edwards');
insert into MARKI values ('86', 'Hicks-Price');
insert into MARKI values ('87', 'Murillo Inc');
insert into MARKI values ('88', 'Lynch, Huff and Marsh');
insert into MARKI values ('89', 'Morgan, Page and Carr');
insert into MARKI values ('90', 'Coleman-White');
insert into MARKI values ('91', 'Robinson-Cobb');
insert into MARKI values ('92', 'Jenkins, Diaz and Hicks');
insert into MARKI values ('93', 'Smith, Washington and Jones');
insert into MARKI values ('94', 'Harper-Cummings');
insert into MARKI values ('95', 'Mcgee-James');
insert into MARKI values ('96', 'Johnson Inc');
insert into MARKI values ('97', 'Rodriguez-Hudson');
insert into MARKI values ('98', 'Fuentes Ltd');
insert into MARKI values ('99', 'Mcdowell, Harrison and Huerta');
